# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fl_app.fl_pb2 as fl__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fl_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FedLearnStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetModel = channel.stream_stream(
                '/fl_app.FedLearn/GetModel',
                request_serializer=fl__pb2.ClientFetchModel.SerializeToString,
                response_deserializer=fl__pb2.ModelReady.FromString,
                _registered_method=True)
        self.ModelPoll = channel.unary_unary(
                '/fl_app.FedLearn/ModelPoll',
                request_serializer=fl__pb2.Ready.SerializeToString,
                response_deserializer=fl__pb2.ReadyReply.FromString,
                _registered_method=True)


class FedLearnServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetModel(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModelPoll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FedLearnServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetModel': grpc.stream_stream_rpc_method_handler(
                    servicer.GetModel,
                    request_deserializer=fl__pb2.ClientFetchModel.FromString,
                    response_serializer=fl__pb2.ModelReady.SerializeToString,
            ),
            'ModelPoll': grpc.unary_unary_rpc_method_handler(
                    servicer.ModelPoll,
                    request_deserializer=fl__pb2.Ready.FromString,
                    response_serializer=fl__pb2.ReadyReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fl_app.FedLearn', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fl_app.FedLearn', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FedLearn(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetModel(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/fl_app.FedLearn/GetModel',
            fl__pb2.ClientFetchModel.SerializeToString,
            fl__pb2.ModelReady.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModelPoll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fl_app.FedLearn/ModelPoll',
            fl__pb2.Ready.SerializeToString,
            fl__pb2.ReadyReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
