# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fl.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'fl.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x66l.proto\x12\x06\x66l_app\"\x16\n\x05Ready\x12\r\n\x05ready\x18\x01 \x01(\t\"\x1b\n\nReadyReply\x12\r\n\x05ready\x18\x01 \x01(\x08\".\n\nUpdateData\x12\r\n\x05model\x18\x01 \x01(\x0c\x12\x11\n\tdata_size\x18\x02 \x01(\x05\"\x85\x01\n\x10\x43lientFetchModel\x12\x14\n\nsend_model\x18\x01 \x01(\x08H\x00\x12(\n\nmodel_data\x18\x02 \x01(\x0b\x32\x12.fl_app.UpdateDataH\x00\x12\x11\n\tclient_id\x18\x03 \x01(\x05\x12\x12\n\nround_time\x18\x04 \x01(\x02\x42\n\n\x08response\"9\n\nModelReady\x12\x0e\n\x04wait\x18\x01 \x01(\x08H\x00\x12\x0f\n\x05model\x18\x02 \x01(\x0cH\x00\x42\n\n\x08response2x\n\x08\x46\x65\x64Learn\x12<\n\x08GetModel\x12\x18.fl_app.ClientFetchModel\x1a\x12.fl_app.ModelReady(\x01\x30\x01\x12.\n\tModelPoll\x12\r.fl_app.Ready\x1a\x12.fl_app.ReadyReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fl_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READY']._serialized_start=20
  _globals['_READY']._serialized_end=42
  _globals['_READYREPLY']._serialized_start=44
  _globals['_READYREPLY']._serialized_end=71
  _globals['_UPDATEDATA']._serialized_start=73
  _globals['_UPDATEDATA']._serialized_end=119
  _globals['_CLIENTFETCHMODEL']._serialized_start=122
  _globals['_CLIENTFETCHMODEL']._serialized_end=255
  _globals['_MODELREADY']._serialized_start=257
  _globals['_MODELREADY']._serialized_end=314
  _globals['_FEDLEARN']._serialized_start=316
  _globals['_FEDLEARN']._serialized_end=436
# @@protoc_insertion_point(module_scope)
